<?php
	return [
		/**
		 *  DEMO FLAG /
		 *  ------------
		 *  Used to flag if the system is to use a demo entry point for 
		 *  First Data
		 */
		'demo' 	=> true,

		/**
		 * API KEY /
		 * ---------
		 *  Your terminal Gateway ID
		 * 
		 */
		'API_KEY' 	=> 'YOUR 8 BIT API KEY',
		/**
		 * API LOGIN /
		 * -----------
		 *  The terminal password generated
		 */
		'API_LOGIN' => 'PASSWORD GENERATED BY THE TERMINAL'
	];
